export const galleryImages = [
    {
        id: 1,
        src: '/gallery/virtual/online01.png',
        alt: 'Neuroscience lesson via Zoom',
        title: 'Exploring the Brain Online',
        caption: 'Students explore the brain during a virtual GRMR lesson led by a volunteer tutor.',
        category: 'vtutoring',
        date: 'July 2021'
    },
    {
        id: 2,
        src: '/gallery/virtual/online02.png',
        alt: 'Volunteer tutors smiling with a student on Zoom',
        title: 'Smiles Across Screens',
        caption: 'Two GRMR tutors connect with their student in a cheerful virtual tutoring session.',
        category: 'vtutoring',
        date: 'July 2021',
    },
    {
        id: 3,
        src: '/gallery/virtual/online03.png',
        alt: 'Two tutors and a student smiling on Zoom',
        title: 'Weekend Smiles and Support',
        caption: 'GRMR tutors foster a supportive environment during a cheerful online session.',
        category: 'vtutoring',
        date: 'July 2021',
    },

    {
        id: 4,
        src: '/gallery/virtual/online04.png',
        alt: 'Student and tutors laughing during a virtual session',
        title: 'Laughter and Learning',
        caption: 'Every GRMR session blends educational support with shared laughter and joy.',
        category: 'vtutoring',
        date: 'July 2021',
    },

    {
        id: 5,
        src: '/gallery/virtual/online05.png',
        alt: 'Child showing animal flashcards during a virtual lesson',
        title: 'Show and Learn',
        caption: 'A student proudly shares animal flashcards during an engaging GRMR tutoring session.',
        category: 'vtutoring',
        date: 'Summer 2021',
    },
    {
        id: 6,
        src: '/gallery/virtual/online06.png',
        alt: 'Student sharing a flower drawing with tutor on Zoom',
        title: 'Creative Confidence',
        caption: 'A student proudly presents her flower drawing during a virtual one-on-one session.',
        category: 'vtutoring',
        date: 'Summer 2021',
    },
    {
        id: 7,
        src: '/gallery/virtual/online07.png',
        alt: 'Tutors and student with parent smiling on Zoom',
        title: 'Family Moments Online',
        caption: 'Tutors brighten a young student’s day with joyful learning alongside his mom.',
        category: 'vtutoring',
        date: 'Summer 2021',
    },
    {
        id: 8,
        src: '/gallery/virtual/online08.png',
        alt: 'Student and tutor smiling during one-on-one virtual session',
        title: 'One-on-One Learning',
        caption: 'Grace and her tutor connect during a focused and friendly virtual session.',
        category: 'vtutoring',
        date: 'Summer 2021',
    },
    {
        id: 9,
        src: '/gallery/virtual/online09.png',
        alt: 'Two tutors smiling with a student on Zoom',
        title: 'Encouraging Every Step',
        caption: 'Tutors support Grace during an engaging and warm virtual learning session.',
        category: 'vtutoring',
        date: 'Summer 2021',
    },
    {
        id: 10,
        src: '/gallery/virtual/online10.png',
        alt: 'Student and tutors holding up flower artwork',
        title: 'Creativity in Bloom',
        caption: 'Students and tutors share colorful flower drawings in a creative Zoom session.',
        category: 'vtutoring',
        date: 'Summer 2021',
    },
    {
        id: 11,
        src: '/gallery/virtual/online11.png',
        alt: 'Tutor and student smiling in a one-on-one Zoom lesson',
        title: 'Focused Learning Time',
        caption: 'Daniel and his tutor connect during an interactive, personalized tutoring session.',
        category: 'vtutoring',
        date: 'March 2022',
    },
    {
        id: 12,
        src: '/gallery/virtual/online12.png',
        alt: 'Student holding drawing while tutor smiles on Zoom',
        title: 'Art and Encouragement',
        caption: 'A young student proudly shares her latest drawing during a virtual art session.',
        category: 'vtutoring',
        date: 'April 2022',
    },
    {
        id: 13,
        src: '/gallery/virtual/online13.png',
        alt: 'Close-up of student smiling during virtual session with Kate Rush',
        title: 'Building Connection',
        caption: 'A joyful student chats with their tutor in a personalized learning session.',
        category: 'vtutoring',
        date: 'April 2022',
    },
    {
        id: 14,
        src: '/gallery/virtual/online14.png',
        alt: 'Zoom call with subtraction worksheet and multiple students participating',
        title: 'Subtract and Succeed',
        caption: 'Students engage in a live subtraction activity led by a GRMR tutor.',
        category: 'vtutoring',
        date: 'April 2022',
    },
    {
        id: 15,
        src: '/gallery/virtual/online15.png',
        alt: 'Tutor and student with interactive math lesson on Zoom',
        title: 'Mastering Math Together',
        caption: 'A student practices place value while the tutor provides real-time guidance.',
        category: 'vtutoring',
        date: 'May 2022',
    },
    {
        id: 16,
        src: '/gallery/virtual/online16.png',
        alt: 'Three-person Zoom session with student drawing a flower',
        title: 'Digital Art Session',
        caption: 'Tutors encourage creativity while a student sketches a flower in real time.',
        category: 'vtutoring',
        date: 'June 2022',
    },
    {
        id: 17,
        src: '/gallery/virtual/online17.png',
        alt: 'Zoom session with parts of speech lesson',
        title: 'Parts of Speech Fun',
        caption: 'Students learn grammar basics during a themed and engaging Zoom lesson.',
        category: 'vtutoring',
        date: 'February 2022',
    },
    {
        id: 18,
        src: '/gallery/virtual/online18.png',
        alt: 'Young student smiling during Zoom session with three other participants',
        title: 'Bright Smiles, Big Goals',
        caption: 'A student beams during a tutoring session focused on encouragement and learning.',
        category: 'vtutoring',
        date: 'June 2021',
    },
    {
        id: 19,
        src: '/gallery/virtual/online19.png',
        alt: 'Tutor and student working on money word problems',
        title: 'Money Matters',
        caption: 'A student practices counting coins while tutors guide them through word problems.',
        category: 'vtutoring',
        date: 'September 2021',
    },
    {
        id: 20,
        src: '/gallery/virtual/online20.png',
        alt: 'Reading comprehension exercise shared over Zoom',
        title: 'Reading for Meaning',
        caption: 'Students build reading skills by discussing comprehension questions with tutors.',
        category: 'vtutoring',
        date: 'April 2022',
    },
    {
        id: 21,
        src: '/gallery/virtual/online21.png',
        alt: 'Zoom session showing math problems involving solving for x',
        title: 'Solving for X',
        caption: 'Students practice solving equations with support from their virtual tutors.',
        category: 'vtutoring',
        date: 'April 2022',
    },
    {
        id: 22,
        src: '/gallery/virtual/online22.png',
        alt: 'Zoom lesson on word search featuring AU sound words',
        title: 'Phonics in Action',
        caption: 'A student completes a word search game focused on AU sounds in English.',
        category: 'vtutoring',
        date: 'April 2022',
    },
    {
        id: 23,
        src: '/gallery/virtual/online23.png',
        alt: 'Three tutors reviewing a triangle area worksheet on Zoom',
        title: 'Breaking Down Geometry',
        caption: 'Tutors guide a student through triangle area problems using shared materials.',
        category: 'vtutoring',
        date: 'May 2022',
    },
    {
        id: 24,
        src: '/gallery/virtual/online24.png',
        alt: 'Zoom session with student and tutors exploring the digital library',
        title: 'Discovering New Stories',
        caption: 'Students browse the digital library with their tutors to find the next great read.',
        category: 'vtutoring',
        date: 'May 2022',
    },
    {
        id: 25,
        src: '/gallery/inperson/event01.jpeg',
        alt: 'Paper plate spiral craft',
        title: 'Hands-On Creativity',
        caption: 'Students experiment with 3D shapes using cut paper plates at an in-person GRMR event.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 26,
        src: '/gallery/inperson/event02.jpeg',
        alt: 'Student building colorful craft',
        title: 'Creative Engineering',
        caption: 'A student presents a colorful, imaginative model built from paper and Play-Doh.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 27,
        src: '/gallery/inperson/event03.jpeg',
        alt: 'Student raising hand in classroom',
        title: 'Engaged in Learning',
        caption: 'A student raises their hand with enthusiasm during a GRMR classroom session.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 28,
        src: '/gallery/inperson/event04.jpeg',
        alt: 'Students celebrating at a table',
        title: 'Celebrating Success',
        caption: 'Excited students cheer during a game-based activity at a GRMR weekend tutoring event.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 29,
        src: '/gallery/inperson/event05.jpeg',
        alt: 'Close-up of kids smiling at camera',
        title: 'Joyful Moments',
        caption: 'Three students pose and smile for a playful close-up at the end of a tutoring session.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 30,
        src: '/gallery/inperson/event06.jpeg',
        alt: 'Child flashing peace signs',
        title: 'Peace and Positivity',
        caption: 'A student flashes double peace signs and smiles during a break at an in-person event.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 31,
        src: '/gallery/inperson/event07.jpeg',
        alt: 'Students working together at a table',
        title: 'Teamwork in Action',
        caption: 'Older students work together on a group assignment, laughing and sharing ideas.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 32,
        src: '/gallery/inperson/event08.jpeg',
        alt: 'Volunteer presenting meteorology lesson',
        title: 'Weather Detectives',
        caption: 'A volunteer leads a lesson on weather and meteorology as students follow along.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 33,
        src: '/gallery/inperson/event09.jpeg',
        alt: 'Student showing hurricane plate project',
        title: 'Hurricane IDA Model',
        caption: 'A student displays their labeled hurricane simulation made from paper plates.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 34,
        src: '/gallery/inperson/event10.jpeg',
        alt: 'Two students holding hurricane wheel crafts',
        title: 'Creative Cyclones',
        caption: 'Two students present their paper hurricane crafts during a weather science lesson.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 35,
        src: '/gallery/inperson/event11.jpeg',
        alt: 'Students working with tape and paper for a structure',
        title: 'Building Together',
        caption: 'Students work in teams to construct paper structures using tape, sticks, and creativity.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 36,
        src: '/gallery/inperson/event12.jpeg',
        alt: 'Volunteer guiding students with structure',
        title: 'Guided Discovery',
        caption: 'A GRMR volunteer supports students during a collaborative engineering activity.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 37,
        src: '/gallery/inperson/event13.jpeg',
        alt: 'Colorful student-made building with Play-Doh',
        title: 'Snack & Structure',
        caption: 'Students show off their creative cardboard-and-clay build while enjoying a cookie break.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 38,
        src: '/gallery/inperson/event14.jpeg',
        alt: 'Orange paper volcano model on a desk',
        title: 'Volcano Showcase',
        caption: 'A close-up of a handmade volcano model, complete with lava and climbing vines.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 39,
        src: '/gallery/inperson/event15.jpeg',
        alt: 'Two students drawing side by side at a table',
        title: 'Quiet Time Drawing',
        caption: 'Students enjoy a peaceful moment coloring their creations at the end of a session.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 40,
        src: '/gallery/inperson/event16.jpeg',
        alt: 'Student raising another in the air playfully',
        title: 'Joyful Lift',
        caption: 'Laughter fills the room as one student lifts another during free time.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 41,
        src: '/gallery/inperson/event17.jpeg',
        alt: 'Tutor writing on board for types of energy',
        title: 'Types of Energy',
        caption: 'Students participate in an interactive lesson about forms of energy like sound and heat.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 42,
        src: '/gallery/inperson/event18.jpeg',
        alt: 'Students playing online Kahoot quiz game',
        title: 'Game-Based Learning',
        caption: 'Students work together on a science quiz game, sharing laughs and answers.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 43,
        src: '/gallery/inperson/event19.jpeg',
        alt: 'Whiteboard message that says “I love you Agnes”',
        title: 'Appreciation Notes',
        caption: 'A sweet message left by a student for their tutor after a day of learning.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 44,
        src: '/gallery/inperson/event20.jpeg',
        alt: 'Group photo with volunteers and students',
        title: 'Smiles All Around',
        caption: 'Volunteers and students pose together at the end of an in-person GRMR lesson.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 45,
        src: '/gallery/inperson/event21.jpeg',
        alt: 'Kids making heart and peace signs with their hands',
        title: 'Love and Laughter',
        caption: 'Students express joy and friendship during a lively GRMR activity.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 46,
        src: '/gallery/inperson/event22.jpeg',
        alt: 'Close-up of student posing with hand on chin',
        title: 'Thinking Cap On',
        caption: 'A student strikes a thoughtful pose while taking a break from an in-person lesson.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 47,
        src: '/gallery/inperson/event23.jpeg',
        alt: 'Student in red shirt smiling at the camera',
        title: 'Confidence in the Classroom',
        caption: 'A student flashes a confident smile during an in-person learning session.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 48,
        src: '/gallery/inperson/event24.jpeg',
        alt: 'Two girls posing with peace signs in front of a mural',
        title: 'Art and Positivity',
        caption: 'Students celebrate the day with peace signs and a colorful mural backdrop.',
        category: 'itutoring',
        date: 'Spring 2025'
    },
    {
        id: 49,
        src: '/gallery/inperson/event25.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 50,
        src: '/gallery/inperson/event26.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 51,
        src: '/gallery/inperson/event27.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 52,
        src: '/gallery/inperson/event28.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 53,
        src: '/gallery/inperson/event28.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 54,
        src: '/gallery/inperson/event29.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 55,
        src: '/gallery/inperson/event30.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 56,
        src: '/gallery/inperson/event31.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 57,
        src: '/gallery/inperson/event32.JPG',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 58,
        src: '/gallery/inperson/event33.jpeg',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 59,
        src: '/gallery/inperson/event34.jpeg',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 60,
        src: '/gallery/inperson/event35.jpeg',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 61,
        src: '/gallery/inperson/event36.jpeg',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 62,
        src: '/gallery/inperson/event37.jpeg',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 63,
        src: '/gallery/inperson/event38.jpeg',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    },
    {
        id: 64,
        src: '/gallery/inperson/event39.jpeg',
        alt: '',
        title: '',
        caption: '',
        category: 'itutoring',
        date: 'Spring 2026'
    }
]